### ISSUE TITLE
TSAL R12

### ISSUE THREAD

**Issue by steinkjn** [michaelruppe/FSAE#9]
Hi Michael,

Thanks for these great designs! My team was reviewing the TSAl v3 design and was wondering about the purpose of R12? Any guidance would be appreciated.

**Comment by michaelruppe** [comment]
R12 is a hysteresis resistor. It is not necessary and can be omitted. In fact, I never populated this in the final build because I preferred to reduce the risk of high voltages appearing at the opamp.

Hysteresis is only really important for high speed circuits generally. This is just a visual indicator hysteresis is not needed - chatter on the output is inconsequential
